package engine

import (
	"fmt"
	"os"
	"path/filepath"
	"time"
)

type PlanMode struct {
	active        bool
	planDir       string
	planFile      string
	readOnlyTools map[string]bool
}

func NewPlanMode(planDir string) *PlanMode {
	return &PlanMode{
		planDir: planDir,
		readOnlyTools: map[string]bool{
			"read_file": true, "list_files": true, "search_code": true,
			"google_web_search": true, "get_session": true, "list_agents": true,
		},
	}
}

func (pm *PlanMode) Activate() error {
	pm.active = true
	if err := os.MkdirAll(pm.planDir, 0755); err != nil {
		return err
	}
	pm.planFile = filepath.Join(pm.planDir, fmt.Sprintf("plan-%s.md", time.Now().Format("20060102-150405")))
	// Write initial plan file
	header := "# Execution Plan\n\n> Generated by Agent Studio Plan Mode\n\n## Tasks\n\n"
	return os.WriteFile(pm.planFile, []byte(header), 0644)
}

func (pm *PlanMode) Deactivate() {
	pm.active = false
}

func (pm *PlanMode) IsActive() bool { return pm.active }

func (pm *PlanMode) IsToolAllowed(toolName string) bool {
	if !pm.active {
		return true
	}
	return pm.readOnlyTools[toolName]
}

func (pm *PlanMode) AppendToPlan(section string) error {
	if pm.planFile == "" {
		return fmt.Errorf("plan mode not activated")
	}
	f, err := os.OpenFile(pm.planFile, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.WriteString(section + "\n\n")
	return err
}

func (pm *PlanMode) ReadPlan() (string, error) {
	if pm.planFile == "" {
		return "", fmt.Errorf("no active plan")
	}
	data, err := os.ReadFile(pm.planFile)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

func (pm *PlanMode) PlanFile() string { return pm.planFile }

func (pm *PlanMode) AddReadOnlyTool(name string) {
	pm.readOnlyTools[name] = true
}
