/// Generates a SOUL.md file from agent configuration data.
/// Follows the 3-section structure from openclaw: Identity, Communication, Boundaries.
class SoulMdGenerator {
  SoulMdGenerator._();

  static String generate(Map<String, dynamic> agent, List<Map<String, dynamic>> gates) {
    final name = agent['name'] ?? 'Agent';
    final bio = agent['bio'] ?? agent['description'] ?? '';
    final role = agent['role'] ?? 'assistant';
    final lore = agent['lore'] ?? '';
    final style = agent['style'] ?? 'Profesional';
    final vocabulary = agent['vocabulary'] ?? '';
    final systemPrompt = agent['system_prompt'] ?? '';
    final tools = (agent['tools'] as List?)?.cast<String>() ?? [];
    final boundaries = (agent['boundaries'] as List?)?.cast<String>() ?? [];

    final buf = StringBuffer();

    // Header
    buf.writeln('# SOUL.md — $name');
    buf.writeln();
    buf.writeln('> Auto-generated by Agent Studio. Do not edit manually.');
    buf.writeln('> Last updated: ${DateTime.now().toIso8601String().split('T')[0]}');
    buf.writeln();

    // Section 1: Identity
    buf.writeln('## Identity');
    buf.writeln();
    buf.writeln('**Name:** $name');
    buf.writeln('**Role:** $role');
    buf.writeln();
    if (bio.isNotEmpty) {
      buf.writeln('### Bio');
      buf.writeln();
      buf.writeln(bio);
      buf.writeln();
    }
    if (lore.isNotEmpty) {
      buf.writeln('### Lore');
      buf.writeln();
      buf.writeln(lore);
      buf.writeln();
    }
    if (systemPrompt.isNotEmpty) {
      buf.writeln('### System Prompt');
      buf.writeln();
      buf.writeln(systemPrompt);
      buf.writeln();
    }

    // Section 2: Communication
    buf.writeln('## Communication');
    buf.writeln();
    buf.writeln('**Style:** $style');
    if (vocabulary.isNotEmpty) {
      buf.writeln();
      buf.writeln('### Vocabulary & Tone');
      buf.writeln();
      buf.writeln(vocabulary);
    }
    buf.writeln();

    // Section 3: Boundaries
    buf.writeln('## Boundaries');
    buf.writeln();
    if (boundaries.isNotEmpty) {
      buf.writeln('### Explicit Deny List');
      buf.writeln();
      for (final b in boundaries) {
        buf.writeln('- $b');
      }
      buf.writeln();
    }

    // Evaluators (Gates)
    if (gates.isNotEmpty) {
      buf.writeln('### Evaluators (Post-Response Checks)');
      buf.writeln();
      for (final gate in gates) {
        final gateName = gate['name'] ?? 'Evaluator';
        final action = gate['action'] ?? 'warn';
        final content = gate['content'] ?? '';
        buf.writeln('#### $gateName');
        buf.writeln();
        buf.writeln('**Action on failure:** $action');
        buf.writeln();
        if (content.isNotEmpty) {
          buf.writeln(content);
          buf.writeln();
        }
      }
    }

    // Tools
    if (tools.isNotEmpty) {
      buf.writeln('## Actions (Tools)');
      buf.writeln();
      for (final tool in tools) {
        buf.writeln('- `$tool`');
      }
      buf.writeln();
    }

    return buf.toString();
  }
}
